name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - 1.3.x
      - 1.2.x

jobs:
  test:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Cache
        uses: coursier/cache-action@v5
      - name: Setup Mill
        uses: jodersky/setup-mill@v0.2.3
      - name: Mill sanity check
        id: mill
        run: mill __.compile
      - name: Documentation
        id: doc
        run: sbt doc
      - name: Test
        id: test
        run: sbt +test
      # Publishing steps
      # These steps are here to avoid duplicated work and logic
      - name: Setup GPG (for Publish)
        id: publish_start
        # on.push.branches above enforces we only publish from correct branches
        if: github.event_name == 'push'
        uses: olafurpg/setup-gpg@v3
      - name: Publish
        # publish_start if guards this step
        if: steps.publish_start.outcome != 'skipped'
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
