name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - 1.5.x
      - 1.3.x
      - 1.2.x

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [ 2.13.4, 2.12.19 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Cache
        uses: coursier/cache-action@v5
      - name: Test
        run: sbt ++${{ matrix.scala }} test

  doc:
    name: Documentation and Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Cache
        uses: coursier/cache-action@v5
      - name: Documentation
        id: doc
        run: sbt doc
      - name: Check Formatting
        run: sbt scalafmtCheckAll

  mill:
    name: Mill Sanity Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Cache
        uses: coursier/cache-action@v5
      - name: Setup Mill
        uses: jodersky/setup-mill@v0.2.3
      - name: Mill sanity check
        id: mill
        run: mill __.compile

  all_tests_passed:
    name: "all tests passed"
    needs: [test, doc, mill]
    runs-on: ubuntu-latest
    steps:
      - run: echo Success!

  publish:
    needs: [all_tests_passed]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Cache Scala
        uses: coursier/cache-action@v5
      - name: Setup GPG (for Publish)
        uses: olafurpg/setup-gpg@v3
      - name: Publish
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
